#!/bin/bash
curl -X 'GET' "http://localhost:3000/posts?tag=2019&tags_in=25&created_at=2018-02-03&dom=dom&dom=dom&dom=dom&dom=dom&dom=dom&dom=dom&dom=dom&dom=dom&dom=dom&dom=dom&dom=dom&dom=dom&dom=dom&dom=dom&dom=dom&dom=dom&dom=dom&dom=dom&dom=dom&dom=dom&page=1"
