#!/bin/bash
curl -X 'POST' "http://localhost:3000/categories?category_name=digggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggm&token=422.hij.8e8539a9dcc14d1e04cd783bb748856072925562"
