#!/bin/bash
curl -X 'POST' "http://localhost:3000/users?password=12345ttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt&first_name=Lilu&last_name=Dalos&user_pic_id=14"
